"""
Introduce test coverage table

Revision ID: dc2f5efc73a1
Revises:     c3dad71f8e6b
Create Date: 2025-11-13 15:40:45.491672
"""

from logging import getLogger

from alembic import op
import sqlalchemy as sa



# Revision identifiers, used by Alembic.
revision = 'dc2f5efc73a1'
down_revision = 'c3dad71f8e6b'
branch_labels = None
depends_on = None


def upgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_coverage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('covered_lines', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_test_coverage_file_id_files'), ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_coverage'))
    )
    op.create_index(op.f('ix_test_coverage_file_id'), 'test_coverage', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_coverage_file_id'), table_name='test_coverage')
    op.drop_table('test_coverage')
    # ### end Alembic commands ###
